version: '3'

services:

  app:
    build: .
    container_name: subscribers-video-catalog
    entrypoint: ./.docker/entrypoint.sh
    volumes:
      - .:/home/node/app
    ports:
      - 3002:3000
    tty: true
